version: '3'

networks:
  net:
    ipam:
      config:
      - subnet: 172.80.0.0/24
        
services:

  php7.3:
    build: ./php-fpm/7.3
    image: vfore_php7.3
    hostname: php7.3
    container_name: php7.3
    ports:
      - '9000:9000'
    networks:
      net:
        ipv4_address: 172.80.0.3
    volumes:
      - /home/server/php/7.3/php.ini:/usr/local/etc/php/php.ini
      - /home/logs/php/:/home/logs/php/
      - /home/www/:/home/www/
    restart: always
    environment:
      - TZ=Asia/Shanghai
    tty: true

  nginx:
    build: ./nginx/
    image: vfore_nginx
    hostname: nginx
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    networks:
      net:
        ipv4_address: 172.80.0.4
    extra_hosts:
      - 'php-fpm:172.80.0.3'
    volumes:
      - /home/server/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/server/nginx/conf.d/:/etc/nginx/conf.d/
      - /home/www/:/home/www/
      - /home/logs/nginx/:/home/logs/nginx/
    restart: always
    environment:
      - TZ=Asia/Shanghai
    tty: true

  mysql8:
    build: ./mysql/8
    image: vfore_mysql8
    hostname: mysql8
    container_name: mysql8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'
    networks:
      net:
        ipv4_address: 172.80.0.2
    volumes:
      - /home/server/mysql/8/data/:/home/server/mysql/data/
      - /home/server/mysql/8/my.cnf:/etc/mysql/my.cnf
      - /home/server/mysql/8/conf.d/:/etc/mysql/conf.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      #MYSQL_ALLOW_EMPTY_PASSWORD: NO
    tty: true